// Code generated by entc, DO NOT EDIT.

package user

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFirstName holds the string denoting the first_name field in the database.
	FieldFirstName = "first_name"
	// FieldLastName holds the string denoting the last_name field in the database.
	FieldLastName = "last_name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldApikey holds the string denoting the apikey field in the database.
	FieldApikey = "apikey"
	// FieldJwttoken holds the string denoting the jwttoken field in the database.
	FieldJwttoken = "jwttoken"
	// FieldActivateCode holds the string denoting the activate_code field in the database.
	FieldActivateCode = "activate_code"
	// FieldActivated holds the string denoting the activated field in the database.
	FieldActivated = "activated"
	// FieldLocked holds the string denoting the locked field in the database.
	FieldLocked = "locked"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"

	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldFirstName,
	FieldLastName,
	FieldEmail,
	FieldPassword,
	FieldApikey,
	FieldJwttoken,
	FieldActivateCode,
	FieldActivated,
	FieldLocked,
	FieldUpdatedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultApikey holds the default value on creation for the apikey field.
	DefaultApikey func() uuid.UUID
	// DefaultActivated holds the default value on creation for the activated field.
	DefaultActivated bool
	// DefaultLocked holds the default value on creation for the locked field.
	DefaultLocked bool
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the id field.
	DefaultID func() uuid.UUID
)
